### ISSUE TITLE
Написать оформленное ТЗ

### ISSUE THREAD

**Issue by trimanul** [trimanul/krDB22#2]
Написать ТЗ, оформленное по ГОСТ 34.602-89.

**Comment by trimanul** [comment]
1.	Техническое задание

1.1.	Общие сведения:
1.1.1.	 Полное наименование системы:
«Система онлайн курсов»

1.1.2.	 Наименования организации-заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н. Э. Баумана
Разработчик: Студент КФ МГТУ им. Н. Э. Баумана группы ИУК5-51Б Кудинов И.В.

1.1.3.	Плановые сроки начала и окончания работы по созданию системы:
Плановый срок начала работ – сентябрь 2022 года.
Плановый срок окончания работ – декабрь 2022 года.

1.1.4.	 Определения, обозначения и сокращения:
-	ПК – Персональный компьютер. 

1.2.	Назначение и цели создания системы
1.2.1.	Назначение системы:
Система предназначена для создания, редактирования и сохранения в базу данных информации об учетных записях пользователей, созданных пользователями курсов.

1.2.2.	 Цели создания системы:
Система разрабатывается для предоставления пользователям удобного способа для создания и просмотра онлайн курсов.

1.3.	Требования к системе

1.3.1.	 Требования к системе в целом:
1.3.1.1.	Требования к структуре и функционированию системы:
Система состоит из клиентской и серверной части. Клиентская часть представляет собой веб-сайт с графическим интерфейсом для взаимодействия пользователя с серверной частью; серверная часть представляет собой базу данных, в которой хранятся данные, и скрипт, взаимодействующий с базой данных.
1.3.1.2.	Требования к численности и квалификации персонала системы и режиму его работы:
Программа рассчитана для одновременной работы множества пользователей. Пользователь должен обладать минимальными навыками работы с ПК на базе ОС Windows, работы с веб-браузером и сетью Интернет.

1.3.1.3.	Требования к надежности:
В случае выхода из строя части системы или всей системы в целом, общая работоспособность ПК должна сохраниться.
 	Программа не должна прекращать работу, если это не требуется специалисту или не предусмотрено сценарием использования программы.
	При непредусмотренном прекращении работы ПК или потере интернет-соединения данные должны быть оставлены без изменений, если пользователь не сохранил эти изменения раньше.

1.3.1.4.	Требования по эргономике и технической эстетике:
Графический интерфейс системы не должен вводить пользователя в заблуждение, содержать элементы, назначение которых неочевидно или элементы, функционал которых отсутствует или не соответствует пояснению в конструкторской документации или непосредственно в интерфейсе, должен быть понятен и не перегружен графическими элементами.

1.3.1.5.	Требования по сохранности информации при авариях:
При сбоях в работе компьютера или при потере интернет-соединения программа закончит работу с потерей несохраненных данных. 
1.3.1.6.	Требования по стандартизации и унификации:
Проектное решение рекомендуется разрабатывать с применением стандартизированных паттернов проектирования программных систем.


1.3.2.	 Требования к функциям (задачам), выполняемым системой

-	Авторизация и регистрация пользователей в системе.
-	Создание новых курсов и просмотр существующих.
-	Добавление в курсы страниц разного назначения: текстовых страниц, страниц с заданиями на написание кода и его автоматической проверкой, страниц с тестовыми заданиями, страниц с мультимедиа-файлами.

1.3.3.	 Требования к видам обеспечения

1.3.3.1.	Требования информационному обеспечению системы
			Данные в системе должны храниться в реляционной базе 			    данных.
1.3.3.2.	Требования к лингвистическому обеспечению системы

В качестве языка программирования для разработки клиентской части приложения используется JavaScript, для разработки серверной части приложения используется Python.
	Средством описания предметной области является русский язык.
	Средством взаимодействия пользователя с системой является русский язык.

1.3.3.3.	Требования к входным и выходным данным

Входными данными системы являются текстовые данные в формате Unicode, мультимедиа-файлы.

1.3.3.4.	Требования к программному обеспечению системы

Веб-браузер, поддерживающий JavaScript.

 
1.4.	 Состав и содержание работ по созданию (развитию) системы

1.	Выбор и согласование темы с руководителем; проведение исследования по выбранной теме, обзор существующих программных продуктов; разработка технического задания (1 – 4-я недели).

2.	Разработка и реализация алгоритмов функционирования приложения, структуры, систем передачи информации, технологий обработки информации и интерфейса взаимодействия пользователя с системой. Выполнение и оформление проектно-конструкторской части работы (5 – 7-я недели).

3.	Тестирование и отладка программного приложения. Разработка руководства пользователя и программиста. Написание проектно-технологической части расчетно-пояснительной записки (9 – 10-я недели).

4.	Завершающее оформление документации согласно требованиям ГОСТ и данного методического пособия. Подготовка доклада. Защита курсовой работы (11 – 14-я недели).

1.5.	 Порядок контроля и приемки системы

Система разрабатывается с применением тестирования работоспособности функционала. При добавлении новых функций предыдущие тесты должны сохранять работоспособность.
Приемка работы осуществляется комиссией КФ МГТУ им. Н. Э. Баумана кафедры ИУК5.

1.6.	 Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие
Для корректной работы системы, на ПК должен быть установлен веб-браузер, поддерживающий JavaScript.








1.7.	 Требования к документированию
Требуется предоставить:
1. Техническое задание в соответствии с ГОСТ 34.602-89
2. Расчетно-пояснительную записку, включающую исследовательскую часть, проектно-конструкторскую часть и проектно-технологическую часть, включающую в себя руководство пользователя и руководство програм¬миста (администратора). Расчетно-пояснительная записка выполняется с учетом требований, предусмотренных ГОСТ 7.32-2001 и 2.105-95.

**Comment by wldmr-key** [comment]
все нормально, но не очень понятно - а пользоваться-то курсами кто-нибудь будет? Судя по описанию, сайт для писателей, а не для читателей ))

**Comment by trimanul** [comment]
Исправил **Назначение системы**:
1.2.1. Назначение системы:
Система предназначена для создания, редактирования и сохранения в базу данных информации об учетных записях пользователей, созданных пользователями курсов. Должна предоставляться возможность удобного просмотра текущих курсов пользователя, прогресса их прохождения и получения оценки качества выполнения заданий. 

Добавил **Требования к функциям (задачам), выполняемым системой**:
- Подписка на курс, добавление курса в списки пользователя (например: «Пройденные», «Не пройденные», «В процессе прохождения») , его прохождение и получение результатов о качестве данных ответов.
-  Сохранение и просмотр прогресса прохождения курса.

**Comment by wldmr-key** [comment]
класс! засчитано
