### ISSUE TITLE
Написать предварительное описание предметной области и требований к системе

### ISSUE THREAD

**Issue by trimanul** [trimanul/krDB22#3]

**Comment by trimanul** [comment]
Система курсов предоставляет пользователям возможность создавать и просматривать курсы. 
Пользователь имеет возможность зарегистрировать свою учетную запись и войти в нее после регистрации. 
    На странице личного кабинета пользователь имеет возможность создавать собственные списки для категоризации и сохранения курсов. Кроме пользовательских у каждой учетной записи имеются 3 автоматически создаваемых списка:
- Пройденные - список, содержащий в себе курсы, которые были пройдены до конца.
- Не пройденные - список, в который пользователь может добавить курсы, которые он собирается просмотреть в будущем.
- В процессе прохождения - курсы, которые еще не были завершены пользователем.

Курс содержит описание, дату создания, ссылку на профиль автора а так же набор отзывов и комментариев других пользователей, которые могут выставлять оценку курсу по 5-балльной шкале.
    Каждый курс является последовательность кадров - отдельных элементов, которыми могут быть:
- Текстовые страницы с учебной информацией, либо мультимедиа страницы с видеоуроками
-  Тестовые задания, после прохождения которых можно сразу получить оценку
-  Задания на написание программного кода с автоматической его проверкой

    Все пользователи веб-сайта делятся на 3 типа: гости, зарегистрированные пользователи и администраторы.
Гости могут просмотреть курс, если в нем не стоит ограничение на просмотр, но не имеют возможности следить за прогрессом его прохождения и другим функционалом авторизованных пользователей.
Администраторы имеют привилегию принудительного удаления  или изменения содержимого курса а также выдачи временной и постоянной блокировки доступа пользователям через специальный интерфейс администратора.
    При наличие в содержимом курсов неприемлемого по мнению пользователя материала имеется возможность подать жалобу на курс, которая появится в администраторской панели.

**Comment by wldmr-key** [comment]
Неплохо
А у всех курсов системы есть ли какая-то общая категоризация? Предметы, например, или чего посложнее?

**Comment by wldmr-key** [comment]
Требования к системе следует прописать более конкретно (я вновь опасаюсь за объем работы)

Все авторизованные пользователи могут создавать курсы?
"Программный код проверяется автоматически" - это будет в системе?
Заполнение тестовых заданий - будет в системе?
Человек, выполнивший тест или контрольную получает обратную связь? Какую? Только оценку? Правильный ответ?

**Comment by trimanul** [comment]
**Добавил:**

> -  Тестовые задания, после прохождения которых можно сразу получить оценку в виде отмеченных правильных и неправильных ответов.

> -  Задания на написание программного кода с автоматической его проверкой. Под автоматической проверкой подразумевается написание функций, которые будут автоматически тестироваться системой на соответствие определенному создателем курса правильному возвращаемому значению.

> Все кадры настраиваются и заполняются автором курса на отдельной странице создания курса: в тестовых заданиях определяются вопросы, варианты ответов и правильные ответы; в заданиях на написание кода определяются такие параметры, как количество памяти, используемое программой, скорость выполнения скрипта и правильное возвращаемое значение.

> Все зарегистрированные пользователи могут создавать курсы.

**Comment by wldmr-key** [comment]
пойдет
