### ISSUE TITLE
Создать предварительную концептуальную схему данных предметной области

### ISSUE THREAD

**Issue by trimanul** [trimanul/krDB22#5]

**Comment by trimanul** [comment]
Концептуальная схема
![Конц  схема](https://user-images.githubusercontent.com/56250764/206927774-5e5d01fa-ba89-46ae-b986-b511c4c32d6e.png)


Логическая схема
![image](https://user-images.githubusercontent.com/56250764/206927803-0d1e9c45-1c2a-4b96-9c87-38d0d0256ff6.png)

**Comment by wldmr-key** [comment]
Концептуальная и логическая схемы не соответствуют описанию предметной области

**Comment by trimanul** [comment]
Добавил недостающие атрибуты и сущность Жалоб
Концептуальная схема
![Конц](https://user-images.githubusercontent.com/56250764/206931666-a061d84a-9e2c-4c4c-ba8a-6bbaea37c5e0.png)

Логическая схема
![лог](https://user-images.githubusercontent.com/56250764/206931682-eeba6efa-6106-4260-9b4d-85737f3b796f.png)

**Comment by wldmr-key** [comment]
прочитай описание предметной области и постарайся устранить все несоответствия

**Comment by trimanul** [comment]
Добавил атрибут даты создания курса, передлал описание предметной области, что бы четче отразить данные, которые пользователь вводит при создании курса, списка и регистрации

Концептуальная схема
 
![Конц](https://user-images.githubusercontent.com/56250764/207015697-ed4f9b7e-0dbf-4f61-9544-4deefcd543a1.png)

Логическая схема

![image](https://user-images.githubusercontent.com/56250764/207015728-1c6c68e0-4862-458e-8bdd-a7f43635c3bd.png)

К сожалению, больше проблем соответствия найти не могу.

**Comment by wldmr-key** [comment]
ок. 

самый грандиозный косяк в том, что тот, кто проходит курс, свой прогресс должен записывать где-то на бумажке (в данных я этого не увидел)

Читаю твое описание предметной области (то, которое мне доступно в репозитории) и сравниваю с концептуальной схемой
Есть в описании, нет в схеме
"наличие определенных материалов", профиль автора,, последовательность страниц (чем определяется последовательность?), " 3 типа: гости, зарегистрированные пользователи и администраторы"

Вижу, что в логической схеме, ты большую часть исправляешь, но именно это и называется "несоответствие" ))
Маленькое несоответствие в логической схеме - в описании ты пишешь про возможность качественного определения длительности курса
Некоторая непонятность - может ли один курс находиться во всех списках пользователя, в частности, в пройденных и не пройденных

**Comment by wldmr-key** [comment]
между пользователями и курсами по-прежнему отсутствует связь "является автором" (в концептуальной схеме. В логической есть)
с новой сущностью счетчики - пока бедлам - не согласуется сописанием никак. Нужны пояснения и не уверен, что она правильная
Я бы советовал, уж, форсировать доделку работы как есть. Бе таких радикальных изменений

**Comment by trimanul** [comment]
Смысл сущности Trackers: когда пользователь нажимает кнопку "Начать курс" для него создается Запись в таблице Trackers(если записи с id пользователя и id страницы еще не существует), которая хранит id страницы, на которой он остановился. Эта запись изменяется с перемещением пользователя по страницам и используется при необходимости(вывод прогресса, переход к последней странице).

Связь добавил:
![Конц](https://user-images.githubusercontent.com/56250764/207111947-ebdfe6cc-4334-4a6e-a065-3af20abb46a3.png)

**Comment by wldmr-key** [comment]
еще раз обращаю внимание - последовательность страниц курса у тебя никак в данных не определяется. Какая первая? следующая? последняя?

Текущая страница у конкретного курса для конкретного пользователя, надеюсь, одна (или 0, если курс не начат)? Судя по схеме это не так

**Comment by trimanul** [comment]
> еще раз обращаю внимание - последовательность страниц курса у тебя никак в данных не определяется. Какая первая? следующая? последняя?

Добавил номер страницы относительно курса в сущность Pages:
![image](https://user-images.githubusercontent.com/56250764/207369436-7e1121f1-081d-45ff-9b5d-0be1d3666e6a.png)

>Текущая страница у конкретного курса для конкретного пользователя, надеюсь, одна (или 0, если курс не начат)? Судя по схеме это не так

Не совсем понимаю, на данный момент Сущность Trackers связана всегда только с одной страницей, я собирался привязать Trackers к Курсам программно, однако могу добавить внешний ключ на таблицу Courses, но тога получится что отношение Trackers-Courses будт один к одному
